### ISSUE TITLE
QoD 0.9 - inline documentation problems

### ISSUE THREAD

**Issue by murthygorty** [camaraproject/QualityOnDemand#199] opened 2023-08-02 22:43 UTC
**Problem description**
Hello, I noticed that we moved to inline documentation. This poses a problem for stakeholders/Product folks or even Devs who just to understand the API quickly without using a tool.
Also, I believe this doesn't meet the check-list requirement for documentation: https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-Readiness-Checklist.md

![image](https://github.com/camaraproject/QualityOnDemand/assets/19613159/360ec3ce-cafe-4631-aa82-ee481b17a204)

Comparatively, 0.8.1 is so much nicer to consume:
https://github.com/camaraproject/QualityOnDemand/blob/release-0.8.1/documentation/API_documentation/QoD_API.md

**Expected action**
Expose documentation that is easy to consume like 0.8.1

**Additional context**
<none - see description>

**Comment by murthygorty** [comment] 2023-08-02 22:44
cc: @gmuratk

**Comment by patrice-conil** [comment] 2023-08-03 08:04
Hi @murthygorty,
Have you tried [swagger online editor](https://editor.swagger.io/) ?
As a developer, I prefer all-in-one specs/docs over separate docs because separate always introduce consistency issues.

**Comment by patrice-conil** [comment] 2023-08-04 09:23
Hi @murthygorty,
Sorry, I was not clear.
I meant as a consumer developer...not as developper of the spec.
I always doubt the accuracy/consistency when I find multiple documents because I know it's hard to maintain.
And yes, we have already included the Markdown documentation in the oas file...so we could include more.

**Comment by patrice-conil** [comment] 2023-08-04 09:27
Besides, I always generate the models and the API from the OAS to be sure not to miss anything.

**Comment by murthygorty** [comment] 2023-08-04 15:36
ahaa, thanks @patrice-conil  - so, if I understood you correctly, are you suggesting that
1) API Developers include all the documentation, markdown (pictures too?) in OAS.
2) before an API is released a tool is run to generate a non-Dev consumable documentation as part of release checklist?

if so, that is perfectly fine, imo.

Without #2 above, I am sorry I cannot agree. CAMARA consumption cannot be for developers only. CAMARA releasechecklist we have is really good and caters to the appropriate audience (including Technical Product Managers in customer organizations who need to create requirements towards Customer Development teams).

If we agree on #1 and #2 above, we still need to fix this issue so that there is a document that is part if 0.9 release :-), don't you agree?
cc: @hdamker @gmuratk

**Comment by patrice-conil** [comment] 2023-08-08 08:04
Hi @murthygorty,
I was just suggesting (1)...but if you really need (2), which I can understand, I don't feel competent to answer.

**Comment by jlurien** [comment] 2023-08-08 10:47
For (2) it would make sense to explore some way to generate a HTML formatted version of the yaml spec, with tools such as [redocly/redoc](https://redocly.com/redoc/), and provide that output as part of the project. This is something transversal to all WGs.

**Comment by jlurien** [comment] 2023-08-10 08:31
I don't think we should go back to what we did in 0.8.x, as that implies duplicating the effort to maintain doc in two different places. If the problem is to provide a non-dev friendly version of the yaml spec, there are some simple ways to provide that in the short term, until we decide to build a proper web hosting of our html versions of the APIs.

For example we could add the URL to the API version (raw) as parameter to
```
https://redocly.github.io/redoc/?url=<url>&nocors
```
and use that in the links in the README.md, as in

## Status and released versions
...
* Release 0.9.0 of the API is available within the [release-0.9.0 branch](https://github.com/camaraproject/QualityOnDemand/tree/release-0.9.0):
  * [API definition with inline documentation](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/QualityOnDemand/release-0.9.0/code/API_definitions/qod-api.yaml&nocors)
  * For changes see [CHANGELOG.md](https://github.com/camaraproject/QualityOnDemand/blob/main/CHANGELOG.md)
* The previous version v0.8.1 of the QoD API is available within the [release-0.8.1 branch](https://github.com/camaraproject/QualityOnDemand/tree/release-0.8.1). 
  * [API definition with inline documentation for 0.8.1](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/QualityOnDemand/release-0.8.1/code/API_definitions/qod-api.yaml&nocors)
...

To avoid external dependencies, another option could be to build the html doc with some Github actions host the files in Github Pages. Similar to [this](https://dmlls.medium.com/redoc-docs-on-gh-pages-97a8926e9e0f)

**Comment by gmuratk** [comment] 2023-08-10 11:20
Shouldn't we take this discussion to the Commonalities subproject to get an explicit guideline for all subprojects?
@shilpa-padgaonkar

**Comment by murthygorty** [comment] 2023-08-10 16:07
Thinking about some more, I completely agree with @gmuratk .
- is the current 0.9.1 compliant with commonalities? If yes, cool! If not, this needs to be fixed (as hotfix?). In parallel, commonalities can be improved as smart here give inputs.

There are two other considerations for merging CAMARA documentation with OAI spec:
1) During my active coding days, in companies where we had inline documentation standard, we kept up well with documenting the interface endpoint and parameters, but the overall documentation at the top of the interface including 'user guide's still had serious bugs from time to time, with inconsistencies.
2) with inline documentation, Carriers may need to upskill tech-writers to write/wordsmith inline documentation. The premise is the OAI developer is not the best at producing final documentation, which is definitely true in my case.
cc: @shilpa-padgaonkar @gmuratk @hdamker

**Comment by eric-murray** [comment] 2023-08-11 10:09
The Swagger editor also supports linking to external documentation, for example:
https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/QualityOnDemand/release-0.9.0/code/API_definitions/qod-api.yaml

I agree such links should be added to the release notes for each release.

With regard to the documentation itself, we need to distinguish between the mechanism by which APIs are documented, and the quality of that documentation. The introductory blurb (under `info: description:`) will always be the hardest to keep up to date, whether it is embedded in the API specification or a standalone markdown document.

But the value of using the API specification as the documentation is that OAS allows individual schema to have descriptions and examples, and good examples and descriptions can be included when the schema is introduced. So this stops documentation being viewed as something to be done right at the end when a new version of the API is otherwise ready.

So I think using these OAS features is the way to go towards keeping documentation up to date. Other tools, such as cucumber, will help to formalise the documentation of expected API behaviour. And whilst I agree that there is an obligation on API developers to try to keep inline documentation up to date and accessible to less technical viewers, I think there is also an obligation on those interested in such details to understand the way in which the associated tooling presents that information.

**Comment by eric-murray** [comment] 2023-08-11 12:10
Agreed at meeting on 11th August to include links to release notes and README. Also raise in Commonalities.

**Comment by eric-murray** [comment] 2023-08-17 15:48
@hdamker
The meeting consensus was to add links to the ReDoc and Swagger Editor formatted versions of a release to both the version release notes, and to the README (for the latest release). So something like:
- Formatted documentation [(Swagger Editor)](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/QualityOnDemand/release-0.9.0/code/API_definitions/qod-api.yaml) [(ReDoc)](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/QualityOnDemand/release-0.9.0/code/API_definitions/qod-api.yaml&nocors)

Can you make the necessary changes? Thanks.

**Comment by jpengar** [comment] 2023-08-18 07:33
If it helps, in HomeDevicesQoD we have this PR https://github.com/camaraproject/HomeDevicesQoD/pull/54 (ready to be merged) that you might want to use as a reference or example. @hdamker @eric-murray @jlurien.

**Comment by hdamker** [comment] 2023-08-21 15:10
> Can you make the necessary changes? Thanks.

Yes, will prepare a PR for that. Thanks for driving the issue to a conclusion.

**Comment by hdamker** [comment] 2023-08-25 11:16
> If it helps, in HomeDevicesQoD we have this PR [camaraproject/HomeDevicesQoD#54](https://github.com/camaraproject/HomeDevicesQoD/pull/54) (ready to be merged) that you might want to use as a reference or example.

@jpengar thanks a lot, copied with pride 👍

**Comment by jpengar** [comment] 2023-08-25 11:58
@hdamker Happy to hear that my PR was useful :)
Remember that the PR updates the README and CHANGELOG files, but you also need to update the release notes accordingly.
https://github.com/camaraproject/QualityOnDemand/releases

**Closed** 2023-08-25 16:02 UTC
Labels: documentation

**Comment by murthygorty** [comment] 2023-08-28 18:28
thank you so much everyone. I feel like we can use QoD as the leading example of CAMARA APIs :-) - it is also very popular for usage as far as I can tell.
